# Generated by Django 5.1 on 2025-07-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citypulse_complaints', '0005_alter_complaint_location_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='location_lat',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='location_lng',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
