# Generated by Django 5.1 on 2025-07-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citypulse_complaints', '0006_alter_complaint_location_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
